runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: 'lllw123456'
  MYSQL_DB: 'bkup'
  MYSQL_HOST: '34.133.219.6'

handlers:
- url: /script
  static_dir: static/script
- url: /styles
  static_dir: static/styles